name: Continuous Integration
on: [push]                      # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v2 # Adds a step to checkout the repository code
    
    - name: Build 
      run: dotnet build

    - name: Run c# Tests
      run: dotnet test

    - name: NPM install/CI
      run: npm ci # Like npm install but uses existing version in lockfile
      working-directory: ./DotnetTemplate.Web

    - name: NPM Build TypeScript
      run: npm run build
      working-directory: ./DotnetTemplate.Web

    - name: Run linter on TypeScript code
      run: npm run lint
      working-directory: ./DotnetTemplate.Web

    - name: Run typeScript Tests
      run: npm t
      working-directory: ./DotnetTemplate.Web

  deploy:
    name: Deploy to Heroku
    needs: build
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v2 # Adds a step to checkout the repository code
    - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "joe-devops-workshop8" #Must be unique in Heroku
        heroku_email: "josephbwo@hotmail.com"
        usedocker: true
